### ISSUE TITLE
Extracting dynamic meta?

### ISSUE THREAD

**Issue by joshuaiz** [manovotny/extract-mdx-metadata#6]
First, thank you for this package - was exactly what I needed.

This is more of a question than an issue but I was trying to use this in a `.mdx` file that had dynamic data from imports like so:

```js
import { joshuaiz } from '@/authors'
import Waveform from '../../../components/Waveform'
import image from './card.jpg'

export const meta = {
  title: "Encapsulating Markup and Styles in Shopify with CodeKit's Hooks and SCSS",
  description: "Keeping your styles with the theme files that use them using CodeKit's Hooks.",
  date: '2020-06-20T18:05:31Z',
  authors: [joshuaiz], // this generates an error
  image, // so does this
}

// rest of content
```
The dynamic values for `authors` and `image` above generate an error with `extract-mdx-metadata`.

As a workaround I changed the values in the `meta` object to strings which works but I was wondering if it is possible to have dynamically generated data extracted?

My guess is no because there is no discreet runtime step to grab the dynamic data...is that correct?

Otherwise, if it *is* possible, it would be a great feature to have.

**Comment by manovotny** [comment]
Intriguing... I don't know if it's possible or not, but there's only one way to find out! 😅 Let me give it a shot and see what I can do. Thanks for raising the question!
